<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-02 at 17:19:26.
 */
class Account_ModelTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var Account_ModelTest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new Account_ModelTest;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Account_Model::userId
     * @todo   Implement testUserId().
     */
    public function testUserId()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Account_Model::password
     * @todo   Implement testPassword().
     */
    public function testPassword()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Account_Model::first_nm
     * @todo   Implement testFirst_nm().
     */
    public function testFirst_nm()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Account_Model::last_nm
     * @todo   Implement testLast_nm().
     */
    public function testLast_nm()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Account_Model::email_addr
     * @todo   Implement testEmail_addr().
     */
    public function testEmail_addr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Account_Model::accCreate_ts
     * @todo   Implement testAccCreate_ts().
     */
    public function testAccCreate_ts()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Account_Model::getUser
     * @todo   Implement testGetUser().
     */
    public function testGetUser()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Account_Model::addUser
     * @todo   Implement testAddUser().
     */
    public function testAddUser()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
