<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-02 at 17:19:29.
 */
class Estimation_ModelTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var Estimation_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new Estimation_Model;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Estimation_Model::act_hr
     * @todo   Implement testAct_hr().
     */
    public function testAct_hr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Estimation_Model::pln_hr
     * @todo   Implement testPln_hr().
     */
    public function testPln_hr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Estimation_Model::start_dt
     * @todo   Implement testStart_dt().
     */
    public function testStart_dt()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Estimation_Model::act_end_dt
     * @todo   Implement testAct_end_dt().
     */
    public function testAct_end_dt()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Estimation_Model::est_end_dt
     * @todo   Implement testEst_end_dt().
     */
    public function testEst_end_dt()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Estimation_Model::est_id
     * @todo   Implement testEst_id().
     */
    public function testEst_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Estimation_Model::getAllEstimates
     * @todo   Implement testGetAllEstimates().
     */
    public function testGetAllEstimates()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
