<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-25 at 21:42:10.
 */
class Generic_ModelTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var Generic_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new Generic_Model;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Generic_Model::__delete
     * @todo   Implement test__delete().
     */
    public function test__delete()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
