<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-02 at 17:19:27.
 */

class Project_ModelTest extends PHPUnit_Framework_TestCase
    {
    /**
     * @var Project_Model
     */
    protected $project;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        
        require_once('Project_Model.php');
        
        $this->project = Project_Model::getProject('0000000001');
        
        
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Project_Model::proj_id
     * @todo   Implement testProj_id().
     */
    public function testProj_id()
        {
        // Remove the following lines when you implement this test.
        assert(is_object($this->project));
        
        }

    /**
     * @covers Project_Model::acc_id
     * @todo   Implement testAcc_id().
     */
    public function testAcc_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::proj_nm
     * @todo   Implement testProj_nm().
     */
    public function testProj_nm()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::proj_descr
     * @todo   Implement testProj_descr().
     */
    public function testProj_descr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::getProject
     * @todo   Implement testGetProject().
     */
    public function testGetProject()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::getAllUserProj
     * @todo   Implement testGetAllUserProj().
     */
    public function testGetAllUserProj()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::deleteProject
     * @todo   Implement testDeleteProject().
     */
    public function testDeleteProject()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::addProject
     * @todo   Implement testAddProject().
     */
    public function testAddProject()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
