<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-02 at 17:19:27.
 */
require('C:/wamp/www/FinalYearProject/Includes/common/Database.class.php');
require('C:/wamp/www/FinalYearProject/Includes/common/Database_Queries.class.php');
require('C:/wamp/www/FinalYearProject/Includes/System/Model/Validator_Model.php');
require('C:/wamp/www/FinalYearProject/Includes/System/Model/Project_Model.php');


class Project_ModelTest extends PHPUnit_Extensions_Database_TestCase
{
    /**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
        $db = new Database();
        return $this->createDefaultDBConnection($db->connect());
    }

    /**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
        return $this->createFlatXMLDataSet(dirname(__FILE__).'/_files/guestbook-seed.xml');
    } 
    /**
     * @var Project_Model
     */
    protected $project;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {

        $this->project = new Project_Model('1');
        $this->assertTrue(is_object($this->project));
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Project_Model::proj_id
     * @todo   Implement testProj_id().
     */
    public function testProj_id()
        {
        // Remove the following lines when you implement this test.
        
        
        }

    /**
     * @covers Project_Model::acc_id
     * @todo   Implement testAcc_id().
     */
    public function testAcc_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::proj_nm
     * @todo   Implement testProj_nm().
     */
    public function testProj_nm()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::proj_descr
     * @todo   Implement testProj_descr().
     */
    public function testProj_descr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::getProject
     * @todo   Implement testGetProject().
     */
    public function testGetProject()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::getAllUserProj
     * @todo   Implement testGetAllUserProj().
     */
    public function testGetAllUserProj()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::deleteProject
     * @todo   Implement testDeleteProject().
     */
    public function testDeleteProject()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Project_Model::addProject
     * @todo   Implement testAddProject().
     */
    public function testAddProject()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
