<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-02 at 17:19:27.
 */
class Staff_ModelTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var Staff_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new Staff_Model;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Staff_Model::staff_id
     * @todo   Implement testStaff_id().
     */
    public function testStaff_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Staff_Model::staff_first_nm
     * @todo   Implement testStaff_first_nm().
     */
    public function testStaff_first_nm()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Staff_Model::staff_last_nm
     * @todo   Implement testStaff_last_nm().
     */
    public function testStaff_last_nm()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Staff_Model::staff_phone
     * @todo   Implement testStaff_phone().
     */
    public function testStaff_phone()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Staff_Model::staff_email
     * @todo   Implement testStaff_email().
     */
    public function testStaff_email()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Staff_Model::getStaffMember
     * @todo   Implement testGetStaffMember().
     */
    public function testGetStaffMember()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Staff_Model::findStaffForTask
     * @todo   Implement testFindStaffForTask().
     */
    public function testFindStaffForTask()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Staff_Model::getStaffForProject
     * @todo   Implement testGetStaffForProject().
     */
    public function testGetStaffForProject()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
