<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-02 at 17:19:29.
 */
class Status_ModelTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var Status_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new Status_Model;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Status_Model::status_id
     * @todo   Implement testStatus_id().
     */
    public function testStatus_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Status_Model::status_cd
     * @todo   Implement testStatus_cd().
     */
    public function testStatus_cd()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Status_Model::status_descr
     * @todo   Implement testStatus_descr().
     */
    public function testStatus_descr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Status_Model::getStatusDescr
     * @todo   Implement testGetStatusDescr().
     */
    public function testGetStatusDescr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
