<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-02 at 17:19:28.
 */
class TaskStatus_ModelTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var TaskStatus_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new TaskStatus_Model;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers TaskStatus_Model::tsk_id
     * @todo   Implement testTsk_id().
     */
    public function testTsk_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers TaskStatus_Model::status_id
     * @todo   Implement testStatus_id().
     */
    public function testStatus_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers TaskStatus_Model::getTaskStatus
     * @todo   Implement testGetTaskStatus().
     */
    public function testGetTaskStatus()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
