<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-02 at 17:19:28.
 */
class Task_ModelTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var Task_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new Task_Model;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Task_Model::tsk_id
     * @todo   Implement testTsk_id().
     */
    public function testTsk_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Task_Model::proj_id
     * @todo   Implement testProj_id().
     */
    public function testProj_id()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Task_Model::tsk_status
     * @todo   Implement testTsk_status().
     */
    public function testTsk_status()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Task_Model::tsk_nm
     * @todo   Implement testTsk_nm().
     */
    public function testTsk_nm()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Task_Model::web_addr
     * @todo   Implement testWeb_addr().
     */
    public function testWeb_addr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Task_Model::tsk_descr
     * @todo   Implement testTsk_dscr().
     */
    public function testTsk_dscr()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Task_Model::getTask
     * @todo   Implement testGetTask().
     */
    public function testGetTask()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Task_Model::getAllTasks
     * @todo   Implement testGetAllTasks().
     */
    public function testGetAllTasks()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Task_Model::editTask
     * @todo   Implement testEditTask().
     */
    public function testEditTask()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
