<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-25 at 21:42:12.
 */
class Validator_ModelTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var Validator_Model
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new Validator_Model;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Validator_Model::variableCheck
     * @todo   Implement testVariableCheck().
     */
    public function testVariableCheck()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Validator_Model::validateEmail
     * @todo   Implement testValidateEmail().
     */
    public function testValidateEmail()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Validator_Model::htmlChar
     * @todo   Implement testHtmlChar().
     */
    public function testHtmlChar()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
