<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-25 at 22:12:14.
 */
class Database_QueriesTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var Database_Queries
     */
    protected $db;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->db = new Database();
        
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers Database_Queries::selectFrom
     * @todo   Implement testSelectFrom().
     */
    public function testSelectFrom()
        {
        // Remove the following lines when you implement this test.
        $this->db->connect();
        }

    /**
     * @covers Database_Queries::deleteFrom
     * @todo   Implement testDeleteFrom().
     */
    public function testDeleteFrom()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers Database_Queries::deleteFrom_String
     * @todo   Implement testDeleteFrom_String().
     */
    public function testDeleteFrom_String()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
