<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-25 at 22:12:13.
 */
class PassHashTest extends PHPUnit_Framework_TestCase
    {

    /**
     * @var PassHash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
        {
        $this->object = new PassHash;
        }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
        {
        
        }

    /**
     * @covers PassHash::unique_salt
     * @todo   Implement testUnique_salt().
     */
    public function testUnique_salt()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers PassHash::hash
     * @todo   Implement testHash().
     */
    public function testHash()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    /**
     * @covers PassHash::check_password
     * @todo   Implement testCheck_password().
     */
    public function testCheck_password()
        {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        }

    }
